spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:3306/chilink
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 1800000       # 30분
  refresh-token-expiration: 1209600000   # 14일

rsa:
  public-key-path: classpath:keys/public.pem
  private-key-path: ${RSA_PRIVATE_KEY_PATH}

firebase:
  credentials:
    path: ${FIREBASE_CREDENTIAL_PATH}
